services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passw00rd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500" 
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: "agent -dev -client=0.0.0.0" 

  postgresql:
    image: postgres:13
    container_name: postgresqlwithsonar
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sonarqube_db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - postgresql
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/sonarqube_db
      - SONAR_JDBC_USERNAME=admin
      - SONAR_JDBC_PASSWORD=123
      - SONARQUBE_JDBC_MAXACTIVE=60
      - SONARQUBE_JDBC_MAXIDLE=5
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=secretsmanager 
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566" 
      - "4571:4571"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
      - seq-logs:/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:
  pgdata:
  seq_data:
  seq-logs:
